server:
  port: 8211
  servlet:
    context-path: /notifications

application:
  email:
      sender: ${EMAIL_SENDER}
  environment: ${ENVIRONMENT:local}
  host: ${HOST:}
  queues:
      coj-received: ${COJ_RECEIVED_QUEUE}
  timezone: Europe/London


com:
  amazonaws:
    xray:
      emitters:
        daemon-address: ${AWS_XRAY_DAEMON_ADDRESS:}

sentry:
  dsn: ${SENTRY_DSN:}
  environment: application.environment
