server:
  port: 8211
  servlet:
    context-path: /notifications

application:
  cache:
    key-prefix: Notifications
    time-to-live: PT24H
  cognito:
    user-pool-id: ${COGNITO_USER_POOL_ID}
  domain: ${APP_DOMAIN:}
  email:
      sender: ${EMAIL_SENDER}
  environment: ${ENVIRONMENT:local}
  queues:
      coj-received: ${COJ_RECEIVED_QUEUE}
      credential-revoked: ${CREDENTIAL_REVOKED_QUEUE}
      form-updated: ${FORM_UPDATED_QUEUE}
  timezone: Europe/London


com:
  amazonaws:
    xray:
      emitters:
        daemon-address: ${AWS_XRAY_DAEMON_ADDRESS:}

sentry:
  dsn: ${SENTRY_DSN:}
  environment: application.environment

spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      ssl:
        enabled: ${REDIS_SSL:false}
      username: ${REDIS_USERNAME:default}
      password: ${REDIS_PASSWORD:password}
