name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  ci-cd:
    name: Build and deploy
    uses: health-education-england/.github/.github/workflows/ci-cd-gradle.yml@main
    with:
      cluster-prefix: trainee
      java-version: |
        21
        17
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}
      reject-pat: ${{ secrets.PAT_REJECT_APPROVALS }}
